{
   "pipe-parallel-size": 1,
   "model-parallel-size": 1,

   "num-layers": 24,
   "hidden-size": 2048,
   "num-attention-heads": 16,
   "seq-length": 2048,
   "max-position-embeddings": 2048,
   "norm": "layernorm",
   "pos-emb": "rotary",
   "rotary_pct": 0.25,
   "no-weight-tying": true,
   "gpt_j_residual": true,
   "output_layer_parallelism": "column",
   
   "scaled-upper-triang-masked-softmax-fusion": true,
   "bias-gelu-fusion": true,


   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.0002,
       "betas": [0.9, 0.95],
       "eps": 0.00000001
     }
   },
   "zero_optimization": {
    "stage": 1,
    "allgather_partitions": true,
    "allgather_bucket_size": 500000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": true,
    "cpu_offload": false
  },
   "min_lr": 0.00002, 

   "train_micro_batch_size_per_gpu": 16,
   "gradient_accumulation_steps": 1,
   "data-impl": "mmap",

   "checkpoint-activations": true,
   "checkpoint-num-layers": 1,
   "partition-activations": true,
   "synchronize-each-layer": true,

   "gradient_clipping": 1.0,
   "weight-decay": 0.1,
   "hidden-dropout": 0,
   "attention-dropout": 0,

   "fp16": {
     "fp16": true,
     "enabled": true,
     "loss_scale": 0,
     "loss_scale_window": 1000,
     "initial_scale_power": 12,
     "hysteresis": 2,
     "min_loss_scale": 1
   },

   "train-iters": 13000,
   "lr-decay-iters": 143000,
   "distributed-backend": "nccl",
   "lr-decay-style": "cosine",
   "warmup": 0.01,
   "checkpoint-factor": 500,
   "eval-interval": 25,
   "eval-iters": 200,
   "keep-last-n-checkpoints": 4,

   "finetune": false,

   "log-interval": 10,
   "steps_per_print": 10,
   "wall_clock_breakdown": true,
        
   "save": "/fsx/mathlm0/proofgpt-v0.4/proofgpt-v0.4-1.4b-12000-early",
   "load": "/fsx/mathlm0/pythia-v2/pythia-1.4b-12000",

   "train-data-paths": ["/fsx/mathlm0/data_v0.2/data_jsonl/train/proof-pile-1.2/proof-pile-1.2_text_document"],
   "valid-data-paths": ["/fsx/mathlm0/data_v0.2/data_jsonl/dev/proof-pile-1.2/proof-pile-1.2_text_document"],
   "test-data-paths": ["/fsx/mathlm0/data_v0.2/data_jsonl/test/proof-pile-1.2/proof-pile-1.2_text_document"],

   "tokenizer-type": "HFTokenizer",
   "vocab-file": "/fsx/pile/20B_tokenizer.json",

   "tensorboard-dir": "/fsx/mathlm0/gpt-neox/tensorboard",
   "log-dir": "/fsx/mathlm0/gpt-neox/logs/",

   "use_wandb": true,
   "wandb_group": "v0.4-1.4b-12000-early",
   "wandb_project": "math-lm-v0.4",
   "wandb_host": "https://api.wandb.ai",

   "launcher": "slurm",
   "deepspeed_slurm": true
}
