{
  # or for weighted datasets:
  "train-data-paths": [
    'data/tokenized300B/train_splits/ArXiv/tokenized_text_document',
    'data/tokenized300B/train_splits/C4/chunk1/tokenized_text_document',
    'data/tokenized300B/train_splits/C4/chunk2/tokenized_text_document',
    'data/tokenized300B/train_splits/C4/chunk3/tokenized_text_document',
    'data/tokenized300B/train_splits/C4/chunk4/tokenized_text_document',
    'data/tokenized300B/train_splits/C4/chunk5/tokenized_text_document',
    'data/tokenized300B/train_splits/C4/chunk6/tokenized_text_document',
    'data/tokenized300B/train_splits/C4/chunk7/tokenized_text_document',
    'data/tokenized300B/train_splits/C4/chunk8/tokenized_text_document',
    'data/tokenized300B/train_splits/C4/chunk9/tokenized_text_document',
    'data/tokenized300B/train_splits/C4/chunk10/tokenized_text_document',
    'data/tokenized300B/train_splits/Github/tokenized_text_document',
    'data/tokenized300B/train_splits/StackExchange/tokenized_text_document',
    'data/tokenized300B/train_splits/CommonCrawl/chunk1/tokenized_text_document',
    'data/tokenized300B/train_splits/CommonCrawl/chunk2/tokenized_text_document',
    'data/tokenized300B/train_splits/CommonCrawl/chunk3/tokenized_text_document',
    'data/tokenized300B/train_splits/CommonCrawl/chunk4/tokenized_text_document',
    'data/tokenized300B/train_splits/CommonCrawl/chunk5/tokenized_text_document',
    'data/tokenized300B/train_splits/CommonCrawl/chunk6/tokenized_text_document',
    'data/tokenized300B/train_splits/CommonCrawl/chunk7/tokenized_text_document',
    'data/tokenized300B/train_splits/CommonCrawl/chunk8/tokenized_text_document',
    'data/tokenized300B/train_splits/CommonCrawl/chunk9/tokenized_text_document',
    'data/tokenized300B/train_splits/CommonCrawl/chunk10/tokenized_text_document'],
  "train-data-weights": [
  2.5,
  1.5419773919518147,
  1.1151591815617388,
  1.5434825189166101,
  1.5436987632648516,
  1.5477789754805582,
  1.5415865562140247,
  1.5418730205678666,
  1.5429308066550182,
  1.5411863039403448,
  1.5403264814471718,
  4.5,
  2.0,
  6.879159444832248,
  4.995774267161819,
  6.872989472503661,
  6.874004825491571,
  6.892691875394247,
  6.889262861528587,
  6.869394427542272,
  6.909669621263436,
  6.915576906743681,
  6.90147629753848
  ],
  "train-dataset-name": 'slim_pajama_workshop',

}

