# GPT-2 pretraining setup
{
  # parallelism settings ( you will want to change these based on your cluster setup, ideally scheduling pipeline stages
  # across the node boundaries )
  "pipe-parallel-size": 1,
  "model-parallel-size": 1, # one copy of the model per node

  # image_prefix settings
  "encoder_name": "openclip-H",
  "pretrained_img_encoder": true,
  "use_image_embed_layernorm": true,
  "image_embed_dropout_prob": 0.1,

  # adapter settings
  "add_adapters": true,
  "adapter_downsample_factor": 8,
  "adapter_type": "lora",

# model settings
  "freeze-lm": true,
  "num-layers": 24,
  "hidden-size": 1024,
  "num-attention-heads": 16,
  "seq-length": 2048,
  "max-position-embeddings": 2048,
  "pos-emb": "rotary",
  "rotary-pct": 0.25,
  "no-weight-tying": true,
  "gpt-j-residual": true,
  "output-layer-parallelism": "column",

  # these should provide some speedup but takes a while to build, set to true if desired
  "scaled-upper-triang-masked-softmax-fusion": true,
  "bias-gelu-fusion": true,

  # init methods
  "init_method": "small_init",
  "output_layer_init_method": "wang_init",

  "zero_optimization": {
    "stage": 1,
    "allgather_partitions": True,
    "allgather_bucket_size": 500000000,
    "overlap_comm": True,
    "reduce_scatter": True,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": True,
    "cpu_offload": False
  },

  # activation checkpointing
  "checkpoint-activations": true,
  "checkpoint-num-layers": 1,
  "partition-activations": true,
  "synchronize-each-layer": true,

  # regularization
  "gradient_clipping": 1.0,
  "weight-decay": 0.0,
  "hidden-dropout": 0.0,
  "attention-dropout": 0.0,

  # precision settings of LLaMa
  "fp16": {
    "enabled": true,
  #  "type": "bfloat16", # set bf16 as precision
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "hysteresis": 2,
    "min_loss_scale": 1
  },

#  "fp32_allreduce": True, # without a patch to torch, bf16 models have to do the allreduce in fp32
  # misc. training settings
  "train-iters": 21600,
  "lr-decay-iters": 21600,
  "distributed-backend": "nccl",
  "lr-decay-style": "cosine",
  "warmup": 0.01,
  "checkpoint-factor": 1000,
  "eval-interval": 1000,
  "eval-iters": 10,

  # logging
  "log-interval": 1,
  "steps_per_print": 1,
  "keep-last-n-checkpoints": 1000,
  "wall_clock_breakdown": true,
}
