# GPT-2 pretraining setup
{
   # parallelism settings ( you will want to change these based on your cluster setup, ideally scheduling pipeline stages
   # across the node boundaries )
   "pipe-parallel-size": 6,
   "model-parallel-size": 2,
   "detect_nvlink_pairs": true,
   #"num_gpus": 12, 
   #"num_nodes": 2,
   "include": "10.141.246.167:0,1,2,3,4,5@10.140.246.238:0,1,2,3,4,5", # will need to change this to your node's ip
   # model settings
   "num-layers": 42,
   "hidden-size": 4096,
   "num-attention-heads": 32,
   "seq-length": 1024,
   "max-position-embeddings": 1024,
   "norm": "layernorm",
   "pos-emb": "learned",
   "no-weight-tying": true,
    # this should provide some speedup but takes a while to build, set to true if desired
   #"scaled-upper-triang-masked-softmax-fusion": true,
   #"bias-gelu-fusion": true,

   
   # optimizer settings
   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.0002,
       "max_grad_norm": 1.0,
       "betas": [0.9, 0.95]
     }
   },
   "zero_optimization": {
    "stage": 0,
    "allgather_partitions": True,
    "allgather_bucket_size": 500000000,
    "overlap_comm": True,
    "reduce_scatter": True,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": True,
    "cpu_offload": False
  },

   # batch / data settings
   #"train_batch_size": 256,
   "train_micro_batch_size_per_gpu": 16,
   "gradient_accumulation_steps": 16,
   "data-impl": "mmap",
   "split": "949,50,1",

   # activation checkpointing
   "checkpoint-activations": true,
   "checkpoint-num-layers": 1,
   "partition-activations": true,
   "synchronize-each-layer": false,

   # regularization
   "gradient_clipping": 1.0,
   "weight-decay": 0,
   "hidden-dropout": 0,
   "attention-dropout": 0,

   # precision settings
   "fp16": { 
     "fp16": true,
     "enabled": true,
     "loss_scale": 0,
     "loss_scale_window": 1000,
     "hysteresis": 2,
     "min_loss_scale": 1
   },

   # misc. training settings
   "train-iters": 320000,
   "lr-decay-iters": 320000,
   "distributed-backend": "nccl",
   "lr-decay-style": "cosine",
   "warmup": 0.01,
   "save-interval": 10000,
   "eval-interval": 1000,
   "eval-iters": 10,

   # logging
   "log-interval": 10,
   "steps_per_print": 10,
   "keep-last-n-checkpoints": 4,
   "wall_clock_breakdown": true,
}
